api/urls.py
from django.conf.urls import patterns, url
from api import views

urlpatterns = patterns('',
    url(r'^authenticate/$', views.auth, name='authenticate'),
    url(r'^reports/$', views.get_reports, name='get_reports'),
    url(r'^files/(?P<report_id>[0-9]+)/$', views.get_file_list, name='get_file_list'),
    url(r'^download/(?P<file_id>[0-9]+)/$', views.get_file, name='get_file'),
    url(r'^report/(?P<report_id>[0-9]+)/$', views.get_report, name='get_report'),
)

group_form/urls.py
from django.conf.urls import patterns, url
from group_form import views

urlpatterns = patterns('', 
url(r'^add-a-member/$', views.add_user, name='add_user'),
)

report_form/urls.py
from django.conf.urls import patterns, url
from report_form import views

urlpatterns = patterns('',
url(r'^make-a-report/$', views.submission, name='submission'),
url(r'^in-dev/$', views.incomplete_landing, name='incomplete_landing'),
url(r'^submitted/$', views.submitted, name='submitted'),
url(r'^my-reports/(?P<user_id>[0-9]+)/$', views.my_reports, name='my_reports'),
url(r'^view-report/(?P<report_id>[0-9]+)/$', views.detail, name='detail'),
url(r'^edit-report/(?P<report_id>[0-9]+)/$', views.edit, name='edit'),
url(r'^download/(?P<file_id>[0-9]+)/$', views.download, name='download'),
url(r'^simple-search/$', views.simple_search, name='simple_search'),
url(r'^advanced-search/$', views.advanced_search, name='advanced_search'),
url(r'^search-with-OR/$', views.search_with_OR, name='search_with_OR'),
url(r'^folder/(?P<folder_id>[0-9]+)/$', views.folder_detail, name='folder_detail'),
url(r'^folder/edit/(?P<folder_id>[0-9]+)/$', views.edit_folder, name='edit_folder'),
url(r'^folder/delete/(?P<folder_id>[0-9]+)/$', views.delete_folder, name='delete_folder'),
url(r'^folder/create/$', views.new_folder, name='new_folder'),
url(r'^reports-index/$', views.view_all_available, name='view_all_available'),
url(r'^latest/$', views.latest_5, name= 'latest_5'),
url(r'^reports-index-dyn/$', views.view_all_available_dynamic, name='view_all_dynamic'),
)

secure_witness/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'secure_witness.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^accounts/register/$', 'secure_witness.views.register'),
    url(r'^accounts/admin/$', 'secure_witness.views.admin_test'),
    url(r'^accounts/profile/$', 'secure_witness.views.profile'),
    url(r'^report_form/', include('report_form.urls', namespace="report_form")),
    url(r'^groups/', include('group_form.urls', namespace="groups")),
    url(r'^swadmin/', include('swadmin.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', RedirectView.as_view(url='accounts/profile')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secure_witness/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
#from group_form.models import Group
#from report_form.models import Permission
import uuid

class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    name = models.CharField(max_length=128, null=True)
    session_token = models.CharField(max_length=255, null=True)
    groups = models.ManyToManyField('group_form.Group')
    admin = models.BooleanField(default=False)
    permissions = models.ManyToManyField('report_form.Permission')

    def generate_token(self):
        return uuid.uuid1().hex

    def __str__(self):
        return self.user.username

User.profile = property(lambda u: UserProfile.objects.get(user=u))
User.is_swadmin = property(lambda u: u.profile.admin)

def is_swadmin(u):
    return u.is_swadmin

secure_witness/forms.py
from secure_witness.models import UserProfile
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('name', )

class user_profile_form(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('name',)

class user_form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

secure_witness/views.py
from django.shortcuts import render_to_response, render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.core.context_processors import csrf
from secure_witness.forms import UserForm, UserProfileForm, user_profile_form
from secure_witness.models import UserProfile, is_swadmin
from report_form.models import Folder
from group_form.models import Group
from  django.contrib.auth.hashers import check_password
import re
@login_required
def profile(request):
    form = user_profile_form()
    form2 = UserForm()
    status = "Edit profile below:"
    user = request.user
    profile = request.user.profile
    groups = Group.objects.filter(users=profile)
    a = re.compile(r'^[\w.@+-]+$')

    if request.method == 'POST':
        if check_password(request.POST['conf_password'], user.password):
            form = user_profile_form(request.POST, instance=request.user.profile)
            form2 = UserForm(request.POST, instance=request.user)
            if request.POST['name'] != '':
                profile.name = request.POST['name'].strip()
            profile.save()
            if request.POST['password'] != '':
                user.password = request.POST['password']
                user.set_password(user.password)
            if request.POST['email'] != '':
                user.email = request.POST['email'].strip()
            if request.POST['username'] != '':
                if len(request.POST['username']) > 30 or not a.match(request.POST['username']):
                    status = "Invalid username."
                    return render(request, 'profile.html',
                  {'form':form, 'groups':groups, 'form2':form2, 'status':status})
                user.username = request.POST['username'].strip()
            user.save()
            status = "Profile update successful."
            #return HttpResponseRedirect('/accounts/profile')
        else:
            status = "Password invalid."



    return render(request, 'profile.html',
                  {'form':form, 'groups':groups, 'form2':form2, 'status':status})


def base(request):
    profile = request.user.profile
    user = request.user
    return render_to_response('base.html', {'admin': request.user.is_swadmin, 'name': profile.name, 'user': user})


def register(request):
    context = RequestContext(request)

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        print("Before")

        if user_form.is_valid() and profile_form.is_valid():
            print("Valid")
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            print("Save")

            registered = True

            f = Folder(name="unsorted", userprofile=profile)
            f.save()
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render_to_response('registration/register.html',
                              {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
                              context)


@login_required
@user_passes_test(is_swadmin)
def admin_test(request):
    print("ADMIN!")
    return render_to_response('profile.html', {'admin': request.user.is_swadmin, 'name': request.user.profile.name})

secure_witness/templates/base.html
{% load staticfiles %}
<html>
  <head>
	  <link rel="stylesheet" type="text/css" href="{% static 'report_form/style.css' %}"/>
	  <title>{% block title %}Secure Witness{% endblock %}</title>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
	  
<style type="text/css">

/*        | CSS Code (c)  Elizabeth Kukla                	 */
/*        |   												 */
/*    	  |													 */
/*   	  |							                   	 */
/*        | Index Internal CSS Style Sheet             		 */

#nav-right {
	float: right;
	text-align: right;
	
	}


</style>


  </head>
  <body>
<!--NAVIGATION BAR-->
    <nav class="navbar-inverse">
      <div class="collapse navbar-collapse">
	<!--LEFT SIDE NAV-->
        <ul class="nav navbar-nav">
            <li><a href="{% url 'report_form:submission' %}">File Report </a></li>
            {% if user != "AnonymousUser" and user.id != None %}
                <li><a href="{% url 'report_form:my_reports' user.id %}">View My Reports </a></li>
                <li><a href="{% url 'groups:add_user' %}"> Add User To Group </a></li>

            {% endif %}
			{% if request.user.is_swadmin %}
				<li><a href="{% url 'swadmin.views.view_users' %}">Manage Users</a></li>		
				<li><a href="{% url 'swadmin.views.view_all_reports' %}">Manage Reports</a></li>	
	  		{% endif %}
      			
		</ul>
		  
		<!--RIGHT SIDE NAV-->	
		<ul class="nav navbar-nav navbar-right">
		<!--DROPDOWN SEARCH MENU-->
			<!--	<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Search <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
			</li>	-->
				<li><a href="{% url 'report_form:search_with_OR' %}">Simple Search </a></li>
      			<li><a href="{% url 'report_form:advanced_search' %}">Advanced Search </a></li>
			{% if user == "AnonymousUser" or user.id == None %}
				<li><a href="{% url 'django.contrib.auth.views.login' %}">Sign In </a></li>
				<li><a href="{% url 'secure_witness.views.register' %}">Sign Up </a></li>
			{% else %}
				<li><a class="nav-right" href="{% url 'secure_witness.views.profile' %}">My Home</a></li>
				<li><a class="nav-right" href="{% url 'django.contrib.auth.views.logout' %}">Log Out </a></li>

			{% endif %}
        	
        
		  </ul>
			
        
      </div>
    </nav><br />

    <div class="container row">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Latest compiled and minified JavaScript -->
  <script src="js/bootstrap.js"></script>
<!--	<script src="js/jquery.js"></script>        
	<script src="js/bootstrap.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>-->

   
  </body>
</html>

secure_witness/templates/profile.html
{% extends "base_reports.html" %}

{% block report_content %}
<div class="body">
<h1>Welcome to Secure Witness, {{ request.user.profile.name }}!</h1><br>
	
    <ul>You are {% if request.user.is_swadmin %} {% else %} not {% endif %} an admin.</ul>

    <ul>Your username is {{ request.user.username }}.</ul>
    <ul>Your e-mail address is {{ request.user.email }}.</ul>
    {% if groups %}
    <ul>You are in the following groups: </ul>
        {% for group in groups %}
        <ul>{{group.name}}</ul>
        {% endfor %}
    {% else %}
        <ul>You are not in any groups :(</ul>
    {% endif %}
        <h2>{{ status }}</h2>
	<div> 
		<br>
		<br>

        <form action="/accounts/profile/" method="post">{% csrf_token %}
        <p><b>New name: </b>
            <input type="text"  name="name" /> </p>
            <p><b>New email: </b>
            <input type="text"  name="email" /> </p>
            <p><b>New username: </b>
            <input type="text"  name="username" /> 30 characters or fewer. Letters, digits and @/./+/-/_ only.</p>
            <p><b>New password: </b>
            <input type="password"  name="password" /> </p>
        <p><b>Confirm your current password: </b>
            <input type="password"  name="conf_password" /> </p>
        <input type="submit" value="Update" />
	</div>
		
		
</div>
{% endblock %}

secure_witness/templates/register.html
{% extends "base.html" %}

{% block content %}

{% if registered %}
  <a href="/accounts/login">Sign in to SecureWitness.</a><br />
{% else %}
  <form id="user_form" method="post" action="/accounts/register/">
      {% csrf_token %}

      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="submit" value="Register" />
  </form>
{% endif %}

{% endblock %}