api/urls.py
from django.conf.urls import patterns, url
from api import views

urlpatterns = patterns('',
    url(r'^authenticate/$', views.auth, name='authenticate'),
    url(r'^reports/$', views.get_reports, name='get_reports'),
    url(r'^files/(?P<report_id>[0-9]+)/$', views.get_file_list, name='get_file_list'),
    url(r'^download/(?P<file_id>[0-9]+)/$', views.get_file, name='get_file'),
    url(r'^report/(?P<report_id>[0-9]+)/$', views.get_report, name='get_report'),
)

report_form/urls.py
from django.conf.urls import patterns, url
from report_form import views

urlpatterns = patterns('',
url(r'^make-a-report/$', views.submission, name='submission'),
url(r'^in-dev/$', views.incomplete_landing, name='incomplete_landing'),
url(r'^submitted/$', views.submitted, name='submitted'),
url(r'^my-reports/(?P<user_id>[0-9]+)/$', views.my_reports, name='my_reports'),
url(r'^view-report/(?P<report_id>[0-9]+)/$', views.detail, name='detail'),
url(r'^edit-report/(?P<report_id>[0-9]+)/$', views.edit, name='edit'),
url(r'^download/(?P<file_id>[0-9]+)/$', views.download, name='download'),
url(r'^simple-search/$', views.simple_search, name='simple_search'),
url(r'^advanced-search/$', views.advanced_search, name='advanced_search'),
url(r'^search-with-OR/$', views.search_with_OR, name='search_with_OR'),
url(r'^folder/(?P<folder_id>[0-9]+)/$', views.folder_detail, name='folder_detail'),
url(r'^folder/edit/(?P<folder_id>[0-9]+)/$', views.edit_folder, name='edit_folder'),
url(r'^folder/delete/(?P<folder_id>[0-9]+)/$', views.delete_folder, name='delete_folder'),
url(r'^folder/create/$', views.new_folder, name='new_folder'),
url(r'^reports-index/$', views.view_all_available, name='view_all_available'),
url(r'^latest/$', views.latest_5, name= 'latest_5'),
url(r'^reports-index-dyn/$', views.view_all_available_dynamic, name='view_all_dynamic'),
)

secure_witness/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'secure_witness.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^accounts/register/$', 'secure_witness.views.register'),
    url(r'^accounts/admin/$', 'secure_witness.views.admin_test'),
    url(r'^accounts/profile/$', 'secure_witness.views.profile'),
    url(r'^report_form/', include('report_form.urls', namespace="report_form")),
    url(r'^groups/', include('group_form.urls', namespace="groups")),
    url(r'^swadmin/', include('swadmin.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', RedirectView.as_view(url='accounts/profile')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swadmin/urls.py
from django.conf.urls import patterns, url
from swadmin import views

urlpatterns = patterns('',
    url(r'^users/$', views.view_users, name='users'),
    url(r'^users/makeadmin/(?P<user_id>[0-9]+)$', views.make_admin, name='users'),
    url(r'^users/suspend/(?P<user_id>[0-9]+)$', views.suspend, name='users'),
    url(r'^users/unsuspend/(?P<user_id>[0-9]+)$', views.unsuspend, name='users'),
    url(r'^groups/$', views.view_groups, name='groups'),
    url(r'^groups/create/$', views.create_group, name='create_group'),
    url(r'^groups/delete/(?P<group_id>[0-9]+)$', views.delete_group, name='delete_group'),
    url(r'^groups/edit/(?P<group_id>[0-9]+)$', views.edit_group, name='edit_group'),
    url(r'^reports/$', views.view_all_reports, name='view_all_reports'),
)

swadmin/views.py
from django.shortcuts import render
from secure_witness.models import is_swadmin
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponseRedirect

from django.contrib.auth.models import User
from group_form.models import Group
from report_form.models import Report, Tag, File
from secure_witness.models import UserProfile

@login_required
@user_passes_test(is_swadmin)
def view_users(request):
    users = User.objects.all()
    user = request.user
    return render(request, 'users.html', {'users': users, 'user': request.user})

@login_required
@user_passes_test(is_swadmin)
def make_admin(request, user_id):
    current = User.objects.filter(id=user_id)[0].profile
    current.admin = True
    current.is_active = True
    current.save()
    return HttpResponseRedirect('/swadmin/users')

@login_required
@user_passes_test(is_swadmin)
def suspend(request, user_id):
    current = User.objects.filter(id=user_id)[0]
    current.is_active = False
    current.save()
    return HttpResponseRedirect('/swadmin/users')

@login_required
@user_passes_test(is_swadmin)
def unsuspend(request, user_id):
    current = User.objects.filter(id=user_id)[0]
    current.is_active = True
    current.save()
    return HttpResponseRedirect('/swadmin/users')

@login_required
@user_passes_test(is_swadmin)
def view_groups(request):
    groups = Group.objects.all()
    user = request.user
    return render(request, 'groups.html', {'groups': groups, 'user': request.user})

@login_required
@user_passes_test(is_swadmin)
def create_group(request):
    current = request.user
    users = UserProfile.objects.all()
    if request.method == "POST":
        name = request.POST["group_name"]
        users = request.POST.getlist("users")

        g = Group(name=name)
        g.save()

        for user in users:
            user = user.strip()
            u = UserProfile.objects.get(pk=user)
            g.users.add(u)

        return HttpResponseRedirect('/swadmin/groups')
    else:
        return render(request, 'create_group.html', {'user': current, 'users': users})

@login_required
@user_passes_test(is_swadmin)
def edit_group(request, group_id):
    current = request.user
    g = Group.objects.get(pk=group_id)
    users_in_group = g.users.all()
    other_users = UserProfile.objects.all()
    for cur_user in users_in_group:
        other_users = other_users.exclude(pk = cur_user.pk)

    if request.method == "POST":
        users_to_delete = request.POST.getlist("users_to_delete")
        users_to_add = request.POST.getlist("users_to_add")

        for user in users_to_delete:
            user = user.strip()
            u = UserProfile.objects.get(pk=user)
            g.users.remove(u)

        for user in users_to_add:
            user = user.strip()
            u = UserProfile.objects.get(pk=user)
            g.users.add(u)

        return HttpResponseRedirect('/swadmin/groups')
    else:
        return render(request, 'edit_group.html', {'user': current, 'users_in_group': users_in_group
            , 'other_users': other_users, 'group': g,})

@login_required
@user_passes_test(is_swadmin)
def delete_group(request, group_id):
    group = Group.objects.get(pk=group_id)
    group.delete()
    return HttpResponseRedirect('/swadmin/groups')

@login_required
@user_passes_test(is_swadmin)
def view_all_reports(request):
    all_reports = Report.objects.all()
    # need to redirect to details
    if request.method == 'POST':
        for indiv in all_reports:
            output = str(indiv.id)
            if request.POST.get(output):
                report_files = File.objects.filter(report=indiv)
                for indiv_file in report_files:
                    indiv_file.delete()
                report_tags = Tag.objects.filter(associated_report=indiv)
                for indiv_tag in report_tags:
                    indiv_tag.delete()
                indiv.delete()
                # want to delete only one at a time
                return HttpResponseRedirect('/swadmin/reports')
        
    return render(request, 'list_reports.html', {'my_reports' : all_reports})  

swadmin/templates/create_group.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8">
  <form method="POST" action="/swadmin/groups/create/">
    {% csrf_token %}
    <label>Group Name:</label><br />
    <input type="text" name="group_name" /><br /><br />
    <label>Select Users to Add to the Group</label><br />
    {% for user in users %}
      <input type="checkbox" value="{{user.user.id}}" name="users" /> {{ user.user.username }}<br />
    {% endfor %}

    <br /><br />

    <input type="submit" value="Create Group" />
  </form>
</div>

<div class="col-md-4">
  <ul class="nav nav-pills nav-stacked">
    <li><a href="/swadmin/users">Users</a></li>
    <li><a href="/swadmin/groups">Groups</a></li>
    <li class="active"><a href="/swadmin/groups/create" style="background: red">+ New Group</a></li>
  </ul>
</div>


{% endblock %}

swadmin/templates/edit_group.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8">
  <form method="POST" action="/swadmin/groups/edit/{{ group.id }}">
    {% csrf_token %}
    <h1>Edit Group "{{ group.name }}"</h1><br />
    <label>Select Users to Add to the Group:</label><br />
      {% if other_users %}
        {% for user in other_users %}
          <input type="checkbox" value="{{user.user.id}}" name="users_to_add" /> {{ user.user.username }}<br />
        {% endfor %}
      {% else %}
        <p>All users are already in this group.</p>
      {% endif %}
      <label>Select Users to Delete from the Group:</label><br />
      {% if users_in_group %}
        {% for user in users_in_group %}
            <input type="checkbox" value="{{user.user.id}}" name="users_to_delete" /> {{ user.user.username }}<br />
        {% endfor %}
      {% else %}
        <p>No users are currently in this group.</p>
      {% endif %}


    <br /><br />

    <input type="submit" value="Edit Group" />
  </form>
</div>

<div class="col-md-4">
  <ul class="nav nav-pills nav-stacked">
    <li><a href="/swadmin/users">Users</a></li>
    <li class="active"><a href="/swadmin/groups">Groups</a></li>
    <li><a href="/swadmin/groups/create" style="color: red;">+ New Group</a></li>
  </ul>
</div>


{% endblock %}

swadmin/templates/groups.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Group Name</th>
        <th>Users</th>
        <th>Delete?</th>
      </tr>
    </thead>
    <tbody>
    {% for group in groups %}
      <tr>
        <td>{{ group.id }}</td>
        <td><a href="/swadmin/groups/edit/{{ group.id }}">{{ group.name }}</a></td>
        <td>
          {% for user in group.users.all %}
          {{ user }}<br />
          {% endfor %}
        </td>
        <td><a href="/swadmin/groups/delete/{{ group.id }}">Delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

</div>
<div class="col-md-4">
  <ul class="nav nav-pills nav-stacked">
    <li><a href="/swadmin/users">Users</a></li>
    <li class="active"><a href="/swadmin/groups">Groups</a></li>
    <li><a href="/swadmin/groups/create" style="color: red;">+ New Group</a></li>
  </ul>
</div>


{% endblock %}

swadmin/templates/list_reports.html
{% extends "base_reports.html" %}

{% block title %}List of Reports{% endblock %}

{% block content %}
	<head>
		<meta charset="utf-8">
		<title>Reports</title>
	</head>
	<body class="body">
	  <div class="div">
		<form class="form"  action = "#" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<h1>Index of Reports</h1>
		{% if my_reports %}
			{% for indiv in my_reports %}
			<p>Description= {{ indiv.short_description }}</p>
			<a href= "{% url 'report_form:detail' indiv.id  %}">
			<button type="button">view submitted report</button></a>
			<input type="submit" name={{ indiv.id }} value="delete report"/>
			{% endfor %}
		{% else %}
			<p> no reports yet submitted </p>
		{% endif %}
		</form>
		</div>
	</body>

{% endblock %}

swadmin/templates/users.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Username</th>
        <th>Name</th>
        <th>Admin?</th>
        <th>Active?</th>
        <th>Make Admin</th>
        <th>Suspend</th>
      </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user }}</td>
          <td>{{ user.profile.name }}</td>
          <td>{{ user.profile.admin }}</td>
          <td>{{ user.is_active }}</td>
          <td>
            {% if user.profile.admin %}
              Is Admin
            {% else %}
              <a href="/swadmin/users/makeadmin/{{ user.id }}">Make Admin</a>
            {% endif %}
          </td>
          <td>
            {% if user.profile.admin %}
              Can't Suspend
            {% elif user.is_active %}
              <a href="/swadmin/users/suspend/{{ user.id }}">Suspend</a>
            {% else %}
            <a href="/swadmin/users/unsuspend/{{ user.id }}">Unsuspend</a>
            {% endif %}
          </td>
        </tr>
    {% endfor %}
    </tbody>
  </table>

</div>
<div class="col-md-4">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="/swadmin/users">Users</a></li>
    <li><a href="/swadmin/groups">Groups</a></li>
    <li><a href="/swadmin/groups/create" style="color: red;">+ New Group</a></li>
  </ul>
</div>


{% endblock %}