api/urls.py
from django.conf.urls import patterns, url
from api import views

urlpatterns = patterns('',
    url(r'^authenticate/$', views.auth, name='authenticate'),
    url(r'^reports/$', views.get_reports, name='get_reports'),
    url(r'^files/(?P<report_id>[0-9]+)/$', views.get_file_list, name='get_file_list'),
    url(r'^download/(?P<file_id>[0-9]+)/$', views.get_file, name='get_file'),
    url(r'^report/(?P<report_id>[0-9]+)/$', views.get_report, name='get_report'),
)

report_form/urls.py
from django.conf.urls import patterns, url
from report_form import views

urlpatterns = patterns('',
url(r'^make-a-report/$', views.submission, name='submission'),
url(r'^in-dev/$', views.incomplete_landing, name='incomplete_landing'),
url(r'^submitted/$', views.submitted, name='submitted'),
url(r'^my-reports/(?P<user_id>[0-9]+)/$', views.my_reports, name='my_reports'),
url(r'^view-report/(?P<report_id>[0-9]+)/$', views.detail, name='detail'),
url(r'^edit-report/(?P<report_id>[0-9]+)/$', views.edit, name='edit'),
url(r'^download/(?P<file_id>[0-9]+)/$', views.download, name='download'),
url(r'^simple-search/$', views.simple_search, name='simple_search'),
url(r'^advanced-search/$', views.advanced_search, name='advanced_search'),
url(r'^search-with-OR/$', views.search_with_OR, name='search_with_OR'),
url(r'^folder/(?P<folder_id>[0-9]+)/$', views.folder_detail, name='folder_detail'),
url(r'^folder/edit/(?P<folder_id>[0-9]+)/$', views.edit_folder, name='edit_folder'),
url(r'^folder/delete/(?P<folder_id>[0-9]+)/$', views.delete_folder, name='delete_folder'),
url(r'^folder/create/$', views.new_folder, name='new_folder'),
url(r'^reports-index/$', views.view_all_available, name='view_all_available'),
url(r'^latest/$', views.latest_5, name= 'latest_5'),
url(r'^reports-index-dyn/$', views.view_all_available_dynamic, name='view_all_dynamic'),
)

secure_witness/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'secure_witness.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^accounts/register/$', 'secure_witness.views.register'),
    url(r'^accounts/admin/$', 'secure_witness.views.admin_test'),
    url(r'^accounts/profile/$', 'secure_witness.views.profile'),
    url(r'^report_form/', include('report_form.urls', namespace="report_form")),
    url(r'^groups/', include('group_form.urls', namespace="groups")),
    url(r'^swadmin/', include('swadmin.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', RedirectView.as_view(url='accounts/profile')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report_form/models.py
from django.db import models
from django.forms import ModelForm
from secure_witness.models import UserProfile
from Crypto.PublicKey import RSA
from django.forms.extras.widgets import SelectDateWidget
from group_form.models import Group

class Folder(models.Model):
    name = models.CharField(max_length=128)
    userprofile = models.ForeignKey(UserProfile)

    def __str__(self):
        return self.name

class Report(models.Model):
    author = models.ForeignKey(UserProfile)
    short_description = models.CharField(max_length=750)
    location = models.CharField(max_length=500, blank=True)
    detailed_description = models.TextField()
    date_of_incident = models.DateField(blank=True, null=True)
    private = models.BooleanField(default=False)
    #time_created = models.DateTimeField(auto_now_add = True);
    time_created = models.TimeField(auto_now_add = True);
    time_last_modified = models.DateTimeField(auto_now = True);
    folder = models.ForeignKey(Folder, blank=True, null=True);
    AES_key= models.CharField(max_length=500, blank=True)
    # don't actually allow this to be null, but we handle this on submission anyway

    def __str__(self):
        return self.short_description

class File(models.Model):
    title = models.CharField(max_length=128) #used to be unique = true... but I was having some errors
    file = models.FileField(upload_to='')#input/%Y/%m/%d
    report = models.ForeignKey(Report)
    hash_code = models.CharField(max_length=500, blank=True, null=True)
    #AES_key= models.CharField(max_length=500)

class Tag(models.Model):
    keyword = models.CharField(max_length=128, null=True, blank=True)
    associated_report = models.ForeignKey(Report)

    def __str__(self):
        return self.keyword

class Permission(models.Model):
    report = models.ForeignKey(Report)
    profiles = models.ManyToManyField(UserProfile)
    groups = models.ManyToManyField(Group)

    def __str__(self):
        output = self.report.short_description
        output += " "
        output += str(self.report.id)
        return output

class ReportForm(ModelForm):
    class Meta:
        model = Report
        fields = ['short_description', 'detailed_description', 'location', 'date_of_incident', 'private']
        widgets = {
        'date_of_incident' : SelectDateWidget,
        }
class FileForm(ModelForm):
    class Meta:
        model = File
        fields = ['file']

class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ['keyword']

report_form/forms.py
from django import forms
from report_form.models import Folder
from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget

AUTHOR = 1
SHORT_DESC = 2
LOCATION = 3
DETAILED_DESC = 4
KEYWORD = 5

SEARCH_CHOICES = (
    (AUTHOR, 'User ID'),
    (SHORT_DESC, 'Short Description'),
    (LOCATION, 'Location'),
    (DETAILED_DESC, 'Detailed Description'),
    (KEYWORD, "Keyword"),
    )


class report_input_form(forms.Form):
    short_description = forms.CharField(label="Short Description: ", max_length=750)
    location = forms.CharField(label="Location of Incident: ", max_length=500, required=False)
    detailed_description = forms.CharField(label="Detailed Description: ", widget=forms.Textarea)
    date_of_incident = forms.DateTimeField(label="Date of Incident: ", required=False,
                                           input_formats=['%m/%d/%Y', '%m/%d/%y'])
    private = forms.BooleanField(label="Private: ", required=False)


class new_folder_form(ModelForm):
    class Meta:
        model = Folder
        fields = ['name']

class multi_cat_search_query(forms.Form):
    search_input = forms.CharField(label="Enter a search string ")
    category = forms.MultipleChoiceField(label ="Search Category", widget=forms.CheckboxSelectMultiple, choices = SEARCH_CHOICES)

class single_search_query(forms.Form):
    search_input = forms.CharField(label="Enter a search string ")
    category = forms.ChoiceField(label ="Search Category", choices = SEARCH_CHOICES)

class multi_field_multi_cat_search(forms.Form):
    s_author = forms.CharField(label="Username ", required=False)
    s_short_desc = forms.CharField(label="Short Description ", required=False)
    s_location = forms.CharField(label="Location ", required=False)
    s_detailed_desc = forms.CharField(label="Detailed Description ", required=False)
    s_keyword = forms.CharField(label="Keyword ", required=False)
    s_date = forms.DateTimeField(label= "Date of Incident ", widget=SelectDateWidget, required=False)

class folder_select(ModelForm):
    folder = forms.ModelChoiceField(queryset=Folder.objects.filter())

report_form/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist

from django.shortcuts import render_to_response

from django.core.context_processors import csrf

from report_form.models import Report, File, ReportForm, Folder, TagForm, Tag, Permission
from report_form.forms import report_input_form, multi_cat_search_query, single_search_query, \
    multi_field_multi_cat_search, new_folder_form
from secure_witness.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.encoding import smart_str
from datetime import date
from django.utils import timezone
from django.core.servers.basehttp import FileWrapper
from group_form.models import Group
from report_form.filter_helper import filter_by_permissions, get_shared_reports, get_5_latest

import os
from report_form.search_helper import simple_return, multi_cat_return, string_parse, advanced_query, multi_cat_return_OR
from Crypto.Cipher import AES
from Crypto import Random
import os
from simplecrypt import encrypt, decrypt
from secure_witness.settings import MEDIA_ROOT
from report_form.validation_helper import permission_validation
from report_form.cryptohelper import get_file_checksum


def incomplete_landing(request):
    return HttpResponse("Report form not yet available.")


@login_required
def my_reports(request, user_id):
    current_user = request.user
    profile = UserProfile.objects.get(user=current_user)
    my_reports = Report.objects.filter(author=profile)
    if request.method == 'POST':
        for indiv in my_reports:
            output = str(indiv.id)
            copy = output + "_copy"
            if request.POST.get(output):
                report_files = File.objects.filter(report=indiv)
                for indiv_file in report_files:
                    indiv_file.delete()
                report_tags = Tag.objects.filter(associated_report=indiv)
                for indiv_tag in report_tags:
                    indiv_tag.delete()
                indiv.delete()
                # want to delete only one at a time
                return HttpResponseRedirect(reverse('report_form:my_reports', args=(profile.user.id,)))
            elif request.POST.get(copy):
                copy_report(indiv.id, profile)
                return HttpResponseRedirect(reverse('report_form:my_reports', args=(profile.user.id,)))
    return render(request, 'report_form/display_list_reports.html', {'my_reports': my_reports, 'profile': profile})


def copy_report(indiv_id, profile):
    print("copy report")
    report = get_object_or_404(Report, pk=indiv_id)
    files = File.objects.filter(report=report)
    tags = Tag.objects.filter(associated_report=report)
    perm = get_object_or_404(Permission, report=report)
    # print(perm)
    r = Report()
    r.author = report.author
    r.short_description = report.short_description
    r.location = report.location
    r.detailed_description = report.detailed_description
    r.private = report.private
    unsorted_folder = Folder.objects.get(userprofile=profile, name='unsorted')
    r.folder = unsorted_folder
    r.save()
    for element in tags:
        t = Tag(associated_report=r)
        t.keyword = element.keyword
        t.save()
    for x in files:
        f = File(report=r)
        f.file = x.file
        f.title = x.title
        f.hash_code = x.hash_code
        f.save()
    p = Permission(report=r)
    print(p)
    p.save()
    for g in perm.groups.all():
        p.groups.add(g)
    for v in perm.profiles.all():
        p.profiles.add(v)
    p.save()


@login_required
def detail(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    files = File.objects.filter(report=report)
    tags = Tag.objects.filter(associated_report=report)
    p = Permission.objects.filter(report=report)
    return render(request, 'report_form/detail.html', {'report': report, 'files': files, 'tags': tags, 'p': p[0], })


@login_required
def edit(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    is_private = report.private
    files = File.objects.filter(report=report)
    tags = Tag.objects.filter(associated_report=report)
    perm = get_object_or_404(Permission, report=report)
    current_user = request.user
    profile = UserProfile.objects.filter(user=current_user)
    groups = Group.objects.filter(users=profile[0])
    if request.method == 'POST':
        request.POST['private'] = is_private
        f = ReportForm(request.POST, instance=report)
        if f.is_valid():
            f.save()
            if report.private:
                #print("encrypt the file")
                for each in request.FILES.getlist("file"):
                    stringkey = report.AES_key
                    key = stringkey.encode(encoding="iso-8859-1", errors="strict")
                    encrypt_file(each, key)
                    newfile = File(title=each.name + ".enc", file=each.name + ".enc", report=report)
                    newfile.save()
                    #newfile = File(title = each.name+".enc", file=each.name+".enc", report=report_input, AES_key=key)
            else:
                for upfile in request.FILES.getlist("file"):
                    newfile = File(title=upfile.name, file=upfile, report=report)
                    newfile.save()
                    path = newfile.file.path
                    hash_code = get_file_checksum(path)
                    newfile.hash_code = hash_code
                    newfile.save()
                    print("from edit " + newfile.hash_code + "****")

            t = TagForm()
            if t.is_valid:
                if request.POST['keyword'] != '':
                    new_tag = Tag(associated_report=report)
                    new_tag.keyword = request.POST['keyword']
                    new_tag.save()
                    # need to alter so that you can add AND DELETE
            viewers = request.POST["viewers"]
            viewers = viewers.split(",")
            g = request.POST.getlist("group_names")
            print(g)
            print(viewers)
            for y in viewers:
                y = y.strip()
                if y != '':
                    status = permission_validation(y, perm.id)
                    print("From edit, status")
                    print(status)
            # issues with addition and deletion is unimplemented
            for x in g:
                x = x.strip()
                gr = Group.objects.get(pk=x)
                perm.groups.add(gr)
            perm.save()

        if request.POST.get("submission"):
            return HttpResponseRedirect(reverse('report_form:detail', args=(report.id,)))
        elif request.POST.get("delete"):
            for inputfile in files:
                # delete here
                if request.POST.get(str(inputfile.id)):
                    inputfile.delete()
                    return HttpResponseRedirect(reverse('report_form:edit', args=(report.id,)))

            return HttpResponse("Report form not yet available.")
        elif request.POST.get("add_kword"):
            return HttpResponseRedirect(reverse('report_form:edit', args=(report.id,)))
        print(request.POST)
        for k in perm.groups.all():
            key = str(k.id)
            key += "_group"
            print(key)
            if request.POST.get(key):
                perm.groups.remove(k)
                perm.save()
                return HttpResponseRedirect(reverse('report_form:edit', args=(report.id,)))
        for m in perm.profiles.all():
            key = str(m.user.id)
            key += "_profile"
            print(key)
            if request.POST.get(key):
                perm.profiles.remove(m)
                perm.save()
                return HttpResponseRedirect(reverse('report_form:edit', args=(report.id,)))
        for t in Tag.objects.all():
            key = str(t.id)
            key += "_kword"
            if request.POST.get(key):
                t.delete()
                return HttpResponseRedirect(reverse('report_form:edit', args=(report.id,)))
        for fi in File.objects.all():
            key = str(fi.id)
            key += "_delete"
            if request.POST.get(key):
                fi.delete()
                return HttpResponseRedirect(reverse('report_form:edit', args=(report.id,)))

        else:
            print(request.POST)
            return HttpResponse("unexpected input widget")
    else:
        print(request.method)
        f = ReportForm(instance=report)
        t = TagForm()

    return render(request, 'report_form/edit.html',
                  {'input_report_form': f, 'report': report, 'files': files, 'input_tag_form': t, 'tags': tags,
                   'groups': groups, 'p': perm})


def submitted(request):
    # want to echo back form fields here for confirmation
    submission = Report.objects.latest('id')  # this is probably not going to work later
    last_id = submission.id
    files = File.objects.filter(report=submission)
    return render(request, 'report_form/submission_template.html', {'submission': submission, 'files': files})


@login_required
def submission(request):
    current_user = request.user
    profile = UserProfile.objects.filter(user=current_user)
    groups = Group.objects.filter(users=profile[0])
    if request.method == 'POST':
        input_report_form = ReportForm(request.POST)
        input_tag_form = TagForm(request.POST)
        if input_report_form.is_valid():
            unsorted_folder = Folder.objects.get(userprofile=profile, name='unsorted')
            report_input = Report()
            report_input.author = profile[0]
            report_input.short_description = request.POST['short_description']

report_form/templates/report_form/create_folder.html
{% extends "base_reports.html" %}

{% block title %}Create Folder{% endblock %}

{% block report_content %}


<div class="col-md-8">
  <form method="POST" action="/report_form/folder/create/">
      {% csrf_token %}
      <h1>New Folder</h1>

      <label>Folder Name:</label><br />
      <input type="text" name="folder_name" /><br /><br />
      <label>Select which Reports to add:</label><br />
      {% if not reports %}
        <p>
            No unsorted reports.<br />
        </p>
      {% endif %}

      {% for report in reports %}
        <input type="checkbox" value="{{report.id}}" name="selected_reports" /> {{ report.short_description }}<br />
      {% endfor %}

    <input type="submit" value="Create Folder" />
  </form>
</div>


{% endblock %}

report_form/templates/report_form/detail.html
{% extends "base_reports.html" %}
{% load filter_by_permissions %}
{% load report_similarity %}

{% block title %}Report Detail{% endblock %}

{% block report_content %}
    <head>
		<meta charset="utf-8">
		<title>Report Detail</title>
	</head>
		<h1>Report Detail</h1>
		{% if report %}
			<p>Author = {{ report.author.user.username }} </p>
			<p>Description = {{ report.short_description }} </p>
			<p>Location = {% if report.location == '' %} None given {% else %} {{report.location}} {% endif %}</p>
			<p>Detailed Description = {{report.detailed_description}} </p>
			<p>Date of Incident = {{report.date_of_incident}} </p>
			<p>Folder = {{report.folder.name }} </p>
			<p>This report is {% if report.private %} private{% else %} public{% endif %}. </p>
			<p><b>Permissions</b></p>
			{% if p.groups.all or p.profiles.all %}
			<ul>
			{% for g in p.groups.all %}
				<li>{{g.name}}</li> 
			{% endfor %}
			</ul>
			<ul>
				{% for v in p.profiles.all %}
				<li>{{v.user.username}}</li>
				{% endfor %}
			</ul>
			{% else %}
			<p>No permissions to show</p>
			{% endif %}
			<p><b>Files </b></p>
			{% if files %}
				<ul>
				{% for inputfile in files %}
					
					<li><a href= "{% url 'report_form:download' inputfile.id %}">{{ inputfile.title }}</a></li>
					
				{% endfor %}
				</ul>
			{% else %}
				<p> No files yet uploaded </p>
			{% endif %}
			<p><b>Keywords </b></p>
			{% if tags %}
				<ul>
				{% for input_tag in tags %}
					<li>{{ input_tag.keyword }}</li>
				{% endfor %}
				</ul>
			{% else %}	
				<p> no keywords associated with this report </p>		
			{% endif %}
			<p>Time Created = {{report.time_created}}</p>
			<p>Time Modified= {{report.time_last_modified}} </p>

		{% else %}
			<p> shouldn't be here </p>
		{% endif %}


        <h2>Similar Reports</h2>
        {% if request.user|similar_reports:report.id%}
			{% for indiv in request.user|similar_reports:report.id %}
                {% if indiv != report and request.user.profile != report.author %}

			        <a href= "{% url 'report_form:detail' indiv.id  %}"><span style="font-size:18px;"><strong>
			        {{ indiv.short_description }}</strong></span></a> - {{ indiv.author }}
                    {% if indiv.date_of_incident %}
                        - {{ indiv.date_of_incident }}
                    {% endif %}
                    <p>{{ indiv.detailed_description|slice:":200" }} ... </p>
                {% endif %}
            {% endfor %}
        {% else %}
            <p> no similar reports to show </p>

		{% endif %}



{% endblock %}

report_form/templates/report_form/display_list_reports.html
{% extends "base_reports.html" %}

{% block title %}My Reports{% endblock %}

{% block report_content %}
	<head>
		<meta charset="utf-8">
		<title>My Reports</title>
	</head>
	<body class="body">
	  <div class="div">
		<form class="form"  action = "{% url 'report_form:my_reports' profile.user.id %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<h1>Reports Submitted</h1>
		{% if my_reports %}
			{% for indiv in my_reports %}
			<p>Description= {{ indiv.short_description }}</p>
			<a href= "{% url 'report_form:detail' indiv.id  %}">
			<button type="button">view submitted report</button></a>
			<a href= "{% url 'report_form:edit' indiv.id  %}">
			<button type="button">edit report</button></a>
			<input type="submit" name={{ indiv.id }} value="delete report"/>
			<input type="submit" name={{ indiv.id }}_copy value="copy report"/>
			{% endfor %}
		{% else %}
			<p> no reports yet submitted </p>
		{% endif %}
		</form>
		</div>
	</body>

{% endblock %}

report_form/templates/report_form/display_search_results.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'report_form/style.css' %}"/>
	<head>
		<meta charset="utf-8">
		<title>Search Results</title>
	</head>
	<body class="body">
	  <div class="div">
		<form class="form"  action = "{% url 'report_form:simple_search' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<h1>Search Query Results</h1>
		{% if results %}
			{% for indiv in results %}
				{% if public_only %}
					{% if not indiv.private %}
						<p>Description= {{ indiv.short_description }}</p>
						<a href= "{% url 'report_form:detail' indiv.id  %}">
						<button type="button">view report</button></a>
					{% endif %}
				{% else %}
					<p>Description= {{ indiv.short_description }}</p>
					<a href= "{% url 'report_form:detail' indiv.id  %}">
					<button type="button">view report</button></a>
				{% endif %}
			{% endfor %}
		{% else %}
			<p> no reports to show </p>
		{% endif %}
		</form>
		</div>
	</body>
</html>

report_form/templates/report_form/edit_folder.html
{% extends "base_reports.html" %}

{% block title %}Edit Folder: "{{folder.name}}"{% endblock %}

{% block report_content %}


<div class="col-md-8">
  <form method="POST" action="{% url 'report_form:edit_folder' folder.id %}">
      {% csrf_token %}
      <h1>Edit Folder: "{{folder.name}}"</h1>
      <label>New Folder Name:</label><br />
      <input type="text" name="folder_name" /><br /><br />
      <label>Select which Reports to add:</label><br />
      {% if not reports %}
        <p>
            No unsorted reports.<br />
        </p>
      {% endif %}

      {% for report in reports %}
        <input type="checkbox" value="{{report.id}}" name="selected_reports" /> {{ report.short_description }}<br />

      {% endfor %}

    <input type="submit" value="Update Folder" />
  </form>
</div>


{% endblock %}

report_form/templates/report_form/folder_detail.html
{% extends "base_reports.html" %}

{% block title %}{{folder.name}}{% endblock %}

{% block report_content %}

	<head>
		<meta charset="utf-8">
		<title>{{folder.name}}</title>
	</head>
	<body class="body">
	  <div class="div">
		<form class="form"  action = "{% url 'report_form:folder_detail' folder.id %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<h1>Reports In Folder "{{folder.name}}"</h1>
            {% if folder.name != "unsorted" %}
                <a href= "{% url 'report_form:edit_folder' folder.id %}">
                <button type="button">edit folder</button></a>
                <a href= "{% url 'report_form:delete_folder' folder.id %}">
                    <button type="button">delete folder</button></a>
			    <br/><br/><br>
            {% endif %}
		{% if reports_in_folder %}
			{% for indiv in reports_in_folder %}
			<p>Description= {{ indiv.short_description }}</p>
			<a href= "{% url 'report_form:detail' indiv.id  %}">
			<button type="button">view submitted report</button></a>
			<a href= "{% url 'report_form:edit' indiv.id  %}">
			<button type="button">edit report</button></a>
			<input type="submit" name={{ indiv.id }} value="delete report"/>
            {% if folder.name != "unsorted" %}
                <input type="submit" name={{ indiv.id }}_folder value="remove from folder"/>
            {% endif %}
			{% endfor %}
        {% else %}
            {% if folder.name == "unsorted" %}
                <p> all reports have been sorted </p>
            {% else %}
			    <p> no reports yet in folder "{{folder.name}}" </p>
            {% endif %}
		{% endif %}
		</form>
		</div>
	</body>

{% endblock %}

report_form/templates/report_form/report_form_template.html
{% extends "base_reports.html" %}
{% load folder_retrieval %}

{% block title %}Create Report{% endblock %}

{% block report_content %}

	<head>
		<meta charset="utf-8">
		<title>Create Report</title>
	</head>
	<body class="body">
	  <div class="div">
		<form class="form"  action = "{% url 'report_form:submission' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<h1>Submit A Report</h1>
			{{ input_report_form.as_p }}
			<p><b>Folder</b></p>
			<select id="folder" name="folder">
			{% for f in request.user.profile|retrieve_folders %}
				<option  value= {{f.id}} > {{f.name}} </option>
			{% endfor %}
				<option  value= {{f.id}} > None </option> <!-- this will be blank, I assume and that is the point-->
				</select>
				<br />
				<br/ >
			<p><i>You don't need to add permissions if your report is public!</i></p>
			<label>Add group visibility</label> <br />
			{% if groups %}
				{% for group in groups %}
				<input type="checkbox" value= {{group.id}} name="group_names"/> {{group.name}} <br />
				{% endfor %}
			{% else %}
			<p>You aren't a member of any group</p>
			{% endif %}	
			<br />
			<label>Add users</label><br />
			<input type="text" name="viewers" /><br /><br />
			<input type="file" name="file" multiple />
			{{ input_tag_form.as_p }}
			<p> <input type="submit" name= "add_kword" value="Add another keyword" /></p>
			<p> <input type="submit" name= "submission" value="Submit Report" /></p>
		</form>
		</div>
	</body>


{% endblock %}

report_form/templates/report_form/view_all_dynamic.html
{% extends "base_reports.html" %}
{% load filter_by_permissions %}

{% block title %}Reports Index{% endblock %}

{% block report_content %}

	<head>
		<meta charset="utf-8">
		<title>Reports Index</title>
	</head>
		<body class="body">
        <div class="div">
        <form class="form"  action = "{% url 'report_form:view_all_dynamic' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<h2>Sort by</h2>
			<select id= 'sort' name='sort'>
                <option  value= "Default" > Default </option>
                <option  value= "location_az" > Location: A to Z </option>
                <option  value= "location_za" > Location: Z to A </option>
                <option  value= "author_az" > Author: A to Z </option>
                <option  value= "author_za" > Author: Z to A </option>
                <option  value= "shortdes_az" > Short Des.: A to Z </option>
                <option  value= "shortdes_za" > Short Des.: Z to A </option>
                <option  value= "created_new" > Date Created: New to Old </option>
                <option  value= "created_old" > Date Created: Old to New </option>
                <option  value= "date_of_incident_new" > Date of Incident: New to Old </option>
                <option  value= "date_of_incident_old" > Date of Incident: Old to New </option>
		    </select>

			<p> <input type="submit" value="Sort" /></p>

		</form>
            </div>
	  <div class="div">
		{% if list_reports %}
			<h1>Reports Shared With Me</h1>
			{% for indiv in list_reports %}
			    {% if indiv.author != user.profile %}
                    <a href= "{% url 'report_form:detail' indiv.id  %}"><span style="font-size:18px;"><strong>
			        {{ indiv.short_description }}</strong></span></a> - {{ indiv.author }}
                    {% if indiv.date_of_incident %}
                        - {{ indiv.date_of_incident }}
                    {% endif %}
                    <p>{{ indiv.detailed_description|slice:":200" }} ... </p>
			    {% endif %}
			{% endfor %}
		{% else %}
			<p> no reports to view </p>
		{% endif %}

		</div>
	</body>
{% endblock %}